# Make sure you podman login to the Red Hat registry, then:
# ansible-builder build -t de_snow:latest -f decision-environment.yml
# To host locally:
# * run the docker registry:
#     podman run -d -p 5000:5000 --name registry registry:latest
# * Add the docker registry as an insecure registry:
#     vi /etc/containers/registries.conf.d/099-localhost-registry.conf
#     
#       [[registry]]
#       location = "localhost:5000"
#       insecure = true
#
# * Tag the built image:
#     podman image tag localhost/de_snow localhost:5000/de_snow
# * Push the image:
#     podman push localhost:5000/de_snow
# * Verify the image is there:
#     curl -X GET http://localhost:5000/v2/_catalog

version: 3

images:
  base_image:
    name: "registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel9:latest"

dependencies:
  galaxy:
    collections:
      - fred.eda

# NOTE: This is required for rhel9 usage
  python_interpreter:
    python_path: /usr/bin/python3.11

options:
  package_manager_path: /usr/bin/microdnf
