---
controller_organizations:
  - name: "virtualization"
    description: "Virtualization Team"
    state: present
    galaxy_credentials:
      - ah_published
      - ah_certified
      - ah_community

controller_credentials:
  - name: "ocp-api-token"
    description: "OpenShift API Bearer Token"
    organization: "virtualization"
    credential_type: "OpenShift or Kubernetes API Bearer Token"
    inputs:
      host: "{{ ocp_host }}"
      verify_ssl: false
      bearer_token: "{{ ocp_token }}"
# type might be kubernetes_bearer_token
  - name: "access-virt-vms-cred"
    description: "Credential to access OpenShift Virtualization VMs via ssh"
    organization: "virtualization"
    credential_type: "Machine"
    inputs:
      username: "fedora"
      ssh_key_data: "{{ ocp_ssh_access_private_key }}"
      # TODO: Generate this data
  - name: "containergroup-sa-token"
    description: "OpenShift API Service Account Token"
    organization: "virtualization"
    credential_type: "OpenShift or Kubernetes API Bearer Token"
    inputs:
      host: "{{ ocp_host }}"
      verify_ssl: false
      bearer_token: "{{ ocp_sa_token }}"

controller_projects:
  - name: "ocpvirt-project"
    description: "Virtualization Demo"
    organization: "virtualization"
    scm_type: git
    scm_url: "https://github.com/derekwaters/ansible_devops_demo.git"
    scm_branch: main
    scm_clean: true
    scm_update_on_launch: true
    update_project: true
    wait: true
    state: present
  - name: "ocpvirt-inventory"
    description: "OpenShift Virtualization Inventory Source"
    organization: "virtualization"
    scm_type: git
    scm_url: "https://github.com/derekwaters/ansible_inventory_sources.git"
    scm_branch: main
    scm_clean: true
    scm_update_on_launch: true
    update_project: true
    wait: true
    state: present

controller_inventories:
  - name: "ocpvirt-vms"
    description: "OpenShift Virtualization Virtual Machines"
    organization: "virtualization"
    state: present

controller_inventory_sources:
  - name: "ocpvirt-vms-source"
    source: "scm"
    inventory: "ocpvirt-vms"
    organization: "virtualization"
    source_project: "ocpvirt-inventory"
    credential: "ocp-api-token"
    # TODO: This should use a service account token
    verbosity: 2
    overwrite: true
    state: present

controller_execution_environments:
  - name: "infra-ee"
    description: "Execution Environment including infra collections"
    organization: "virtualization"
    image: "quay.io/rh-ee-dwaters/infra-ee"
    state: present

controller_instance_groups:
  - name: "ocpvirt-cluster-exec"
    credential: "containergroup-sa-token"
    is_container_group: true
    pod_spec_override:
      apiVersion: v1
      kind: Pod
      metadata:
        namespace: aap-exec
      spec:
        serviceAccountName: containergroup-service-account
        automountServiceAccountToken: false
        containers:
          image: >-
            registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8@sha256:880dadb7f632ba574721e94aaa1909993ec7b36101001101395a26d1ae379627
          name: worker
          args:
            - ansible-runner
            - worker
            - '--private-data-dir=/runner'
          resources:
            requests:
              cpu: 250m
              memory: 100Mi
    state: present

controller_templates:
  - name: "patch-vms"
    playbook: "{{ demo_name }}/playbooks/patch-vms.yml"
    job_type: "run"
    organization: "virtualization"
    inventory: "ocpvirt-vms"
    project: "ocpvirt-project"
    limit: "namespace_{{ vmnamespace | default('vms-namespace') | replace('-', '_') }}"
    instance_groups:
      - "ocpvirt-cluster-exec"
    ask_variables_on_launch: true
    credentials:
      - "access-virt-vms-cred"
    state: present

  - name: "add-vm-to-inventory"
    playbook: "{{ demo_name }}/playbooks/add-vm-to-inventory.yml"
    job_type: "run"
    organization: "virtualization"
    inventory: "Demo Inventory"
    project: "ocpvirt-project"
    execution_environment: "infra-ee"
    ask_variables_on_launch: true
    extra_vars:
      controller_hostname: "{{ controller_hostname }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"
    credentials:
      - "Demo Credential"
    state: present

  - name: "add-vm-to-cmdb"
    playbook: "{{ demo_name }}/playbooks/add-vm-to-cmdb.yml"
    job_type: "run"
    organization: "virtualization"
    inventory: "Demo Inventory"
    project: "ocpvirt-project"
    ask_variables_on_launch: true
    extra_vars:
      ocp_host: "{{ ocp_host }}"
      ocp_token: "{{ ocp_sa_token }}"
      # TODO: Make this the OCPVirt service account token
      snow_instance: "{{ snow_instance }}"
      snow_username: "{{ snow_username }}"
      snow_password: "{{ snow_password }}"
    credentials:
      - "Demo Credential"
    state: present

controller_workflows:
  - name: "add-vm-and-patch"
    description: "Add a new OCPVirt VM to the CMDB inventory and apply patches"
    organization: "virtualization"
    inventory: "Demo Inventory"
    state: present
    ask_variables_on_launch: true
    simplified_workflow_nodes:
      - identifier: add-vm
        unified_job_template: "add-vm-to-inventory"
        success_nodes:
          - "patch-vms"
          - "add-vm-to-cmdb"
        failure_nodes: []
        always_nodes: []
        credentials: []

      - identifier: patch-vms
        unified_job_template: "patch-vms"
        success_nodes: []
        failure_nodes: []
        always_nodes: []
        credentials: []

      - identifier: add-vm-to-cmdb
        unified_job_template: "add-vm-to-cmdb"
        success_nodes: []
        failure_nodes: []
        always_nodes: []
        credentials: []
...
