---
- name: Remediate Web Server from ServiceNow Incident
  hosts: "{{ target_host_name | default(omit) }}"
  gather_facts: false

  tasks: 
    - name: Start HTTPD Service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      become: true

    - name: Validate Web Server works
      ansible.builtin.uri:
        url: http://localhost

    - name: Gather HTTPD error log
      ansible.builtin.copy:
        src: /var/log/httpd/error_log
        dest: /tmp/httpd_error.log
        remote_src: true
      become: true

    - name: Gather journal log
      ansible.builtin.shell: "journalctl -u httpd.service"
      register: journal_log

    - name: Create journal file
      ansible.builtin.copy:
        content: "{{ journal_log }}"
        dest: /tmp/httpd_journal.log
      delegate_to: localhost

    - name: Gather messages log
      ansible.builtin.shell: "echo 'httpd is down' > /tmp/{{ inc_number }}_messages.log"
      register: messages_log
    - name: Gather journal /var/log/messages
      ansible.builtin.shell: "echo 'Mar 29 06:03:03 ip-10-0-1-116.us-east-2.compute.internal systemd[1]: Stopped The Apache HTTP Server.' > /tmp/{{ inc_number }}_journal.log"
      register: journal_log

    - name: Update an incident in ServiceNow
      servicenow.itsm.incident:
        # state: in_progress
        number: "{{ inc_number }}"
        attachments:
          - path: "/tmp/{{ inc_number }}_messages.log"
            name: "{{ inc_number }}_messages.log"
          - path: "/tmp/{{ inc_number }}_journal.log"
            name: "{{ inc_number }}_journal.log"
      delegate_to: localhost
    
    # - name: Attach the log files
    #   servicenow.itsm.attachment_upload:
    #     table_name: incident
    #     table_sys_id: "{{ inc_sys_id }}"
    #     attachments:
    #       - path: "/tmp/{{ inc_number }}_messages.log"
    #         name: "{{ inc_number }}_messages.log"
    #       - path: "/tmp/{{ inc_number }}_journal.log"
    #         name: "{{ inc_number }}_journal.log"
    #       # - path: "/tmp/httpd_error.log"
    #       #   name: "error_messages.log"
    #       # - path: "/tmp/httpd_journal.log"
    #       #   name: "httpd_journal.log"
    #   delegate_to: localhost

    # - name: Update Incident with augmentation
    #   servicenow.itsm.api:
    #     resource: incident
    #     action: patch
    #     sys_id: "{{ inc_sys_id }}"
    #     data:
    #       work_notes: "Event Driven Ansible has augmented this incident with log files. AAP Job Id: {{ tower_job_id }}"
    #   register: snow_var
    #   delegate_to: localhost

