---
- name: Remediate Web Server from ServiceNow Incident
  hosts: "{{ target_host_name | default(omit) }}"
  gather_facts: false

  tasks: 
    - name: Start HTTPD Service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      become: true

    - name: Validate Web Server works
      ansible.builtin.uri:
        url: http://localhost

    - name: Gather HTTPD error log
      ansible.builtin.fetch:
        src: /var/log/httpd/error_log
        dest: /tmp/
        flat: yes
      become: true

    - name: Gather journal log
      ansible.builtin.shell: "journalctl -u httpd.service"
      register: journal_log

    - name: Create journal file
      ansible.builtin.copy:
        content: "{{ journal_log }}"
        dest: /tmp/httpd_journal.log
      delegate_to: localhost

    - name: Update an incident in ServiceNow
      servicenow.itsm.problem:
        short_description: Add HTTPD logs
        attachments:
          - path: "/tmp/error_log"
            name: "httpd_error.log"
          - path: "/tmp/httpd_journal.log"
            name: "httpd_journal.log"
      register: problem
      delegate_to: localhost
    
    - name: Update an incident in ServiceNow
      servicenow.itsm.incident:
        state: in_progress
        number: "{{ inc_number }}"
        other:
          problem_id: "{{ problem.record.sys_id }}"
      delegate_to: localhost


