---
- name: Remediate Web Server from ServiceNow Incident
  hosts: "{{ target_host_name | default(omit) }}"
  gather_facts: false

  tasks: 
    - name: Start HTTPD Service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      become: true

    - name: Validate Web Server works
      ansible.builtin.uri:
        url: http://localhost

    - name: Gather HTTPD error log
      ansible.builtin.copy:
        src: /var/log/httpd/error_log
        dest: /tmp/httpd_error.log
        remote_src: true
      become: true

    - name: Gather journal log
      ansible.builtin.shell: "journalctl -u httpd.service"
      register: journal_log

    - name: Create journal file
      ansible.builtin.copy:
        content: "{{ journal_log }}"
        dest: /tmp/httpd_journal.log
      delegate_to: localhost

    - name: Attach the log files
      servicenow.itsm.attachment_upload:
        table_name: incident
        table_sys_id: "{{ inc_sys_id }}"
        attachments:
          - path: "/tmp/httpd_error.log"
            name: "error_messages.log"
          # - path: "/tmp/httpd_journal.log"
          #   name: "httpd_journal.log"
      delegate_to: localhost

    - name: Update Incident with augmentation
      servicenow.itsm.api:
        resource: incident
        action: patch
        sys_id: "{{ inc_sys_id }}"
        data:
          work_notes: "Event Driven Ansible has augmented this incident with log files. AAP Job Id: {{ tower_job_id }}"
      register: snow_var
      delegate_to: localhost

