---
- name: Create ServiceNow Incident
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Create an incident in ServiceNow
      servicenow.itsm.incident:
        state: new
        description: "{{ sn_description | default(omit) }}"
        short_description: "{{ incident_description }}"
        caller: admin
        urgency: "{{ sn_urgency }}"
        impact: "{{ sn_impact }}"
        other:
          u_operating_system: "{{ os | default(omit) }}"
          u_ip_address: "{{ sn_ci_ip_address | default(omit) }}"
          u_vm_name: "{{ sn_ci_hostname | default(omit) }}"
      register: new_incident

    - name: Display incident number
      ansible.builtin.debug:
        var: new_incident.record.number