- name: Get ServiceNow Incident
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Debug all vars
      ansible.builtin.debug:
        var: ansible_eda
  
    - name: Set the incident number and sys id
      ansible.builtin.set_fact:
        inc_number: "{{ ansible_eda.event.number }}"
        inc_sys_id: "{{ ansible_eda.event.sys_id }}"

    - name: Getting CI Detail
      servicenow.itsm.configuration_item_info:
        sys_id: "{{ ansible_eda.event.cmdb_ci.value }}"
      register: ci_detail

    - name: Debug CI Name
      ansible.builtin.debug:
        msg: "CI Name: {{ ci_detail.records[0].name }}"

    - name: Set_Stats Successful Status
      ansible.builtin.set_stats:
        data:
          inc_number: "{{ ansible_eda.event.number }}"
          inc_sys_id: "{{ ansible_eda.event.sys_id }}"
          target_host_name: "{{ ci_detail.records[0].name }}"
